#!/usr/bin/env python3
"""Write copy-paste prompts + sizes for the cookbook's illustrations.

This calls no image API. It generates ILLUSTRATIONS.md: one self-contained prompt
and a recommended size per recipe, all in a single locked watercolour-and-ink
style, so any image tool (e.g. Google's "nano banana" / Gemini 2.5 Flash Image)
produces a coherent set. Save each result as assets/illustrations/recipes/<slug>.png
and the build prefers it over the SVG placeholder automatically (no front-matter edit).

Run: python3 tools/illustration_prompts.py
"""
from __future__ import annotations

from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parent.parent
RECIPES = ROOT / "recipes"
OUT = ROOT / "ILLUSTRATIONS.md"

# The shared style suffix — appended to every recipe prompt so the whole set
# matches. Generalised from the project's reference example.
STYLE = (
    "loose expressive ink outlines, transparent watercolor washes, soft cast shadow "
    "beneath the dish, realistic but painterly, modern cookbook illustration, a single "
    "isolated subject on a fully transparent background, no backdrop, no scenery, "
    "no text or lettering"
)

SIZE = (
    "3:2 landscape — generate at the largest size your tool offers "
    "(nano banana / Gemini ≈ 1024 px on the long edge; upscale toward ~1500 px wide "
    "for crisp print), and export as a PNG with a transparent background"
)


def subject(title_lc: str, hay: str) -> str:
    """A dish-specific subject phrase (with its own leading article)."""
    def has(*ks: str) -> bool:
        return any(k in hay for k in ks)

    if has("cheesecake"):
        return (f"a slice of {title_lc} with a buttery biscuit base on a ceramic plate, "
                "a wheel of lime and a sprig of mint beside it")
    if has("fondant", "lava", "molten"):
        return (f"a {title_lc}, a molten chocolate cake with a soft oozing centre, "
                "dusted with icing sugar, on a ceramic plate")
    if has("mousse", "pudding", "panna cotta"):
        return f"a {title_lc} served in a small glass, topped with whipped cream and a dusting of cocoa"
    if has("congolais", "macaroon", "cookie", "biscuit", "meringue"):
        return f"a small pile of {title_lc} on a ceramic plate, lightly golden"
    if has("pate", "lorrain", "pie", "pastry", "tart", "quiche", "empanada", "roll"):
        return f"a {title_lc}, a golden flaky baked pastry on a ceramic plate, a sprig of herbs beside it"
    if has("rice", "arroz", "risotto", "pilaf", "bowl", "soup", "stew", "curry", "salad", "chili"):
        return f"a bowl of {title_lc} served in a ceramic bowl, garnished with fresh herbs"
    if has("tea", "infusion", "coffee", "latte"):
        return f"a cup of {title_lc}, hot, with gently rising steam and a slice of lemon on the saucer"
    if has("pancake", "waffle", "crepe", "stack"):
        return f"a short stack of {title_lc} on a ceramic plate, drizzled with syrup, fresh fruit on top"
    if has("cake", "gateau", "sponge", "loaf", "tarte"):
        return (f"a {title_lc} on a ceramic plate, golden crust, moist crumb, "
                "one slice cut and leaning against the cake")
    return f"a serving of {title_lc} on a ceramic plate"


def prompt_for(title: str, hay: str) -> str:
    return (f"A hand-painted watercolor and ink cookbook illustration of "
            f"{subject(title.lower(), hay)}, {STYLE}.")


def load() -> list[dict]:
    out = []
    for p in sorted(RECIPES.glob("*.md")):
        fm = yaml.safe_load(p.read_text(encoding="utf-8").split("---", 2)[1]) or {}
        out.append({"slug": fm.get("slug", p.stem), "title": fm.get("title", p.stem),
                    "tags": fm.get("tags", []) or []})
    return out


def main() -> int:
    lines = [
        "# Illustration prompts",
        "",
        "> Generated by `tools/illustration_prompts.py` — re-run it after adding recipes.",
        "",
        "Each recipe needs one hero illustration. Generate it with any image model "
        "(these prompts are tuned for Google's **nano banana** / Gemini 2.5 Flash Image, "
        "but work anywhere), then **save it as the PNG path shown** — the build "
        "automatically prefers that PNG over the bundled SVG placeholder, with no "
        "front-matter changes.",
        "",
        "All prompts share one locked watercolour-and-ink style so the set stays "
        "coherent. Generate on a **transparent background** and export a **PNG** (or "
        "WebP) so the page's cream paper and grain show through cleanly — the soft "
        "cast shadow keeps the dish grounded on the page. (If your tool can't make a "
        "true transparent background, generate on a plain flat colour and remove it, "
        "watching for edge fringing.)",
        "",
        f"**Recommended size for every recipe image:** {SIZE}.",
        "",
        "---",
        "",
    ]
    for r in load():
        lines += [
            f"### {r['title']}",
            "",
            f"- **Save as:** `assets/illustrations/recipes/{r['slug']}.png`",
            "",
            "```text",
            prompt_for(r["title"], f"{r['title']} {r['slug']} {' '.join(r['tags'])}".lower()),
            "```",
            "",
        ]

    lines += [
        "---",
        "",
        "## Decorative pages (optional)",
        "",
        "The cover, endpapers and back use generated white **line-art** patterns on "
        "navy (`assets/illustrations/patterns/*.svg`). To replace them with AI art, "
        "generate **2:3 portrait, full-bleed (≈1024×1536)** images, save as "
        "`patterns/cover.png` / `endpaper.png` / `back.png`, and point the matching "
        "`url(...)` in `assets/css/print.css` at the new file.",
        "",
        "```text",
        "A seamless full-bleed pattern of simple single continuous-line white ink "
        "drawings of food (vegetables, fruit, jars, utensils, plates, bottles) evenly "
        "scattered on a deep navy background (#16203a), minimal line-art style, "
        "consistent line weight, no fills, no text.",
        "```",
        "",
    ]
    OUT.write_text("\n".join(lines), encoding="utf-8")
    print(f"wrote {OUT.relative_to(ROOT)} ({len(load())} recipe prompts)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
